sudo: false

language: python

matrix:
  include:
    # Python 3.4
    - python: "3.4"
      os: "linux"
      dist: trusty
      env: TOXENV=py34

    # Python 3.5
    - python: "3.5"
      os: "linux"
      dist: trusty
      env: TOXENV=py35

    # Python 3.6
    - python: "3.6"
      os: "linux"
      dist: trusty
      env: TOXENV=py36

    # Linters
    - python: "3.6"
      os: "linux"
      dist: trusty
      env: TOXENV=linters

  allow_failures:
    - env: TOXENV=linters

cache:
  directories:
    - $PWD/wheelhouse  # cache wheels so that we don't hit network every time
env:
  global:
    - PIP_FIND_LINKS=$PWD/wheelhouse

install:
  - pip install tox-travis

script: tox